/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as DashboardSubmitDecisionRouteImport } from './routes/dashboard/submit-decision'
import { Route as DashboardSubmitRouteImport } from './routes/dashboard/submit'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardMyReviewsRouteImport } from './routes/dashboard/my-reviews'
import { Route as DashboardEthicalGuideRouteImport } from './routes/dashboard/ethical-guide'
import { Route as DashboardAssignedArticlesRouteImport } from './routes/dashboard/assigned-articles'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthProfileRouteImport } from './routes/auth/profile'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles/$articleId'
import { Route as DashboardManageUsersRouteImport } from './routes/dashboard/manage/users'
import { Route as DashboardArticlesArticlesRouteImport } from './routes/dashboard/articles/articles'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubmitDecisionRoute = DashboardSubmitDecisionRouteImport.update({
  id: '/dashboard/submit-decision',
  path: '/dashboard/submit-decision',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubmitRoute = DashboardSubmitRouteImport.update({
  id: '/dashboard/submit',
  path: '/dashboard/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyReviewsRoute = DashboardMyReviewsRouteImport.update({
  id: '/dashboard/my-reviews',
  path: '/dashboard/my-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEthicalGuideRoute = DashboardEthicalGuideRouteImport.update({
  id: '/dashboard/ethical-guide',
  path: '/dashboard/ethical-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAssignedArticlesRoute =
  DashboardAssignedArticlesRouteImport.update({
    id: '/dashboard/assigned-articles',
    path: '/dashboard/assigned-articles',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManageUsersRoute = DashboardManageUsersRouteImport.update({
  id: '/dashboard/manage/users',
  path: '/dashboard/manage/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardArticlesArticlesRoute =
  DashboardArticlesArticlesRouteImport.update({
    id: '/dashboard/articles/articles',
    path: '/dashboard/articles/articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/assigned-articles': typeof DashboardAssignedArticlesRoute
  '/dashboard/ethical-guide': typeof DashboardEthicalGuideRoute
  '/dashboard/my-reviews': typeof DashboardMyReviewsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard/submit-decision': typeof DashboardSubmitDecisionRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/articles/articles': typeof DashboardArticlesArticlesRoute
  '/dashboard/manage/users': typeof DashboardManageUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/assigned-articles': typeof DashboardAssignedArticlesRoute
  '/dashboard/ethical-guide': typeof DashboardEthicalGuideRoute
  '/dashboard/my-reviews': typeof DashboardMyReviewsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard/submit-decision': typeof DashboardSubmitDecisionRoute
  '/articles': typeof ArticlesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/articles/articles': typeof DashboardArticlesArticlesRoute
  '/dashboard/manage/users': typeof DashboardManageUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/assigned-articles': typeof DashboardAssignedArticlesRoute
  '/dashboard/ethical-guide': typeof DashboardEthicalGuideRoute
  '/dashboard/my-reviews': typeof DashboardMyReviewsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard/submit-decision': typeof DashboardSubmitDecisionRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/articles/articles': typeof DashboardArticlesArticlesRoute
  '/dashboard/manage/users': typeof DashboardManageUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms'
    | '/articles/$articleId'
    | '/auth/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/assigned-articles'
    | '/dashboard/ethical-guide'
    | '/dashboard/my-reviews'
    | '/dashboard/reviews'
    | '/dashboard/submit'
    | '/dashboard/submit-decision'
    | '/articles/'
    | '/dashboard/'
    | '/dashboard/articles/articles'
    | '/dashboard/manage/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms'
    | '/articles/$articleId'
    | '/auth/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/assigned-articles'
    | '/dashboard/ethical-guide'
    | '/dashboard/my-reviews'
    | '/dashboard/reviews'
    | '/dashboard/submit'
    | '/dashboard/submit-decision'
    | '/articles'
    | '/dashboard'
    | '/dashboard/articles/articles'
    | '/dashboard/manage/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms'
    | '/articles/$articleId'
    | '/auth/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/assigned-articles'
    | '/dashboard/ethical-guide'
    | '/dashboard/my-reviews'
    | '/dashboard/reviews'
    | '/dashboard/submit'
    | '/dashboard/submit-decision'
    | '/articles/'
    | '/dashboard/'
    | '/dashboard/articles/articles'
    | '/dashboard/manage/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DashboardAssignedArticlesRoute: typeof DashboardAssignedArticlesRoute
  DashboardEthicalGuideRoute: typeof DashboardEthicalGuideRoute
  DashboardMyReviewsRoute: typeof DashboardMyReviewsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSubmitRoute: typeof DashboardSubmitRoute
  DashboardSubmitDecisionRoute: typeof DashboardSubmitDecisionRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardArticlesArticlesRoute: typeof DashboardArticlesArticlesRoute
  DashboardManageUsersRoute: typeof DashboardManageUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/submit-decision': {
      id: '/dashboard/submit-decision'
      path: '/dashboard/submit-decision'
      fullPath: '/dashboard/submit-decision'
      preLoaderRoute: typeof DashboardSubmitDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/submit': {
      id: '/dashboard/submit'
      path: '/dashboard/submit'
      fullPath: '/dashboard/submit'
      preLoaderRoute: typeof DashboardSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-reviews': {
      id: '/dashboard/my-reviews'
      path: '/dashboard/my-reviews'
      fullPath: '/dashboard/my-reviews'
      preLoaderRoute: typeof DashboardMyReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ethical-guide': {
      id: '/dashboard/ethical-guide'
      path: '/dashboard/ethical-guide'
      fullPath: '/dashboard/ethical-guide'
      preLoaderRoute: typeof DashboardEthicalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/assigned-articles': {
      id: '/dashboard/assigned-articles'
      path: '/dashboard/assigned-articles'
      fullPath: '/dashboard/assigned-articles'
      preLoaderRoute: typeof DashboardAssignedArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manage/users': {
      id: '/dashboard/manage/users'
      path: '/dashboard/manage/users'
      fullPath: '/dashboard/manage/users'
      preLoaderRoute: typeof DashboardManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/articles/articles': {
      id: '/dashboard/articles/articles'
      path: '/dashboard/articles/articles'
      fullPath: '/dashboard/articles/articles'
      preLoaderRoute: typeof DashboardArticlesArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DashboardAssignedArticlesRoute: DashboardAssignedArticlesRoute,
  DashboardEthicalGuideRoute: DashboardEthicalGuideRoute,
  DashboardMyReviewsRoute: DashboardMyReviewsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSubmitRoute: DashboardSubmitRoute,
  DashboardSubmitDecisionRoute: DashboardSubmitDecisionRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardArticlesArticlesRoute: DashboardArticlesArticlesRoute,
  DashboardManageUsersRoute: DashboardManageUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
