/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as DashboardSubmitRouteImport } from './routes/dashboard/submit'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardMyArticlesRouteImport } from './routes/dashboard/my-articles'
import { Route as DashboardMainRouteImport } from './routes/dashboard/main'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthProfileRouteImport } from './routes/auth/profile'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles/$articleId'
import { Route as DashboardManageUsersRouteImport } from './routes/dashboard/manage/users'
import { Route as DashboardManageArticlesRouteImport } from './routes/dashboard/manage/articles'
import { Route as DashboardArticlesArticleIdRouteImport } from './routes/dashboard/articles/$articleId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubmitRoute = DashboardSubmitRouteImport.update({
  id: '/dashboard/submit',
  path: '/dashboard/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyArticlesRoute = DashboardMyArticlesRouteImport.update({
  id: '/dashboard/my-articles',
  path: '/dashboard/my-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMainRoute = DashboardMainRouteImport.update({
  id: '/dashboard/main',
  path: '/dashboard/main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManageUsersRoute = DashboardManageUsersRouteImport.update({
  id: '/dashboard/manage/users',
  path: '/dashboard/manage/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManageArticlesRoute = DashboardManageArticlesRouteImport.update({
  id: '/dashboard/manage/articles',
  path: '/dashboard/manage/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardArticlesArticleIdRoute =
  DashboardArticlesArticleIdRouteImport.update({
    id: '/dashboard/articles/$articleId',
    path: '/dashboard/articles/$articleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/main': typeof DashboardMainRoute
  '/dashboard/my-articles': typeof DashboardMyArticlesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/articles/$articleId': typeof DashboardArticlesArticleIdRoute
  '/dashboard/manage/articles': typeof DashboardManageArticlesRoute
  '/dashboard/manage/users': typeof DashboardManageUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/main': typeof DashboardMainRoute
  '/dashboard/my-articles': typeof DashboardMyArticlesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/dashboard/articles/$articleId': typeof DashboardArticlesArticleIdRoute
  '/dashboard/manage/articles': typeof DashboardManageArticlesRoute
  '/dashboard/manage/users': typeof DashboardManageUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/main': typeof DashboardMainRoute
  '/dashboard/my-articles': typeof DashboardMyArticlesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/articles/$articleId': typeof DashboardArticlesArticleIdRoute
  '/dashboard/manage/articles': typeof DashboardManageArticlesRoute
  '/dashboard/manage/users': typeof DashboardManageUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms'
    | '/articles/$articleId'
    | '/auth/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/main'
    | '/dashboard/my-articles'
    | '/dashboard/reviews'
    | '/dashboard/submit'
    | '/articles/'
    | '/dashboard/articles/$articleId'
    | '/dashboard/manage/articles'
    | '/dashboard/manage/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms'
    | '/articles/$articleId'
    | '/auth/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/main'
    | '/dashboard/my-articles'
    | '/dashboard/reviews'
    | '/dashboard/submit'
    | '/articles'
    | '/dashboard/articles/$articleId'
    | '/dashboard/manage/articles'
    | '/dashboard/manage/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms'
    | '/articles/$articleId'
    | '/auth/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/main'
    | '/dashboard/my-articles'
    | '/dashboard/reviews'
    | '/dashboard/submit'
    | '/articles/'
    | '/dashboard/articles/$articleId'
    | '/dashboard/manage/articles'
    | '/dashboard/manage/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DashboardMainRoute: typeof DashboardMainRoute
  DashboardMyArticlesRoute: typeof DashboardMyArticlesRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSubmitRoute: typeof DashboardSubmitRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DashboardArticlesArticleIdRoute: typeof DashboardArticlesArticleIdRoute
  DashboardManageArticlesRoute: typeof DashboardManageArticlesRoute
  DashboardManageUsersRoute: typeof DashboardManageUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/submit': {
      id: '/dashboard/submit'
      path: '/dashboard/submit'
      fullPath: '/dashboard/submit'
      preLoaderRoute: typeof DashboardSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-articles': {
      id: '/dashboard/my-articles'
      path: '/dashboard/my-articles'
      fullPath: '/dashboard/my-articles'
      preLoaderRoute: typeof DashboardMyArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/main': {
      id: '/dashboard/main'
      path: '/dashboard/main'
      fullPath: '/dashboard/main'
      preLoaderRoute: typeof DashboardMainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manage/users': {
      id: '/dashboard/manage/users'
      path: '/dashboard/manage/users'
      fullPath: '/dashboard/manage/users'
      preLoaderRoute: typeof DashboardManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manage/articles': {
      id: '/dashboard/manage/articles'
      path: '/dashboard/manage/articles'
      fullPath: '/dashboard/manage/articles'
      preLoaderRoute: typeof DashboardManageArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/articles/$articleId': {
      id: '/dashboard/articles/$articleId'
      path: '/dashboard/articles/$articleId'
      fullPath: '/dashboard/articles/$articleId'
      preLoaderRoute: typeof DashboardArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DashboardMainRoute: DashboardMainRoute,
  DashboardMyArticlesRoute: DashboardMyArticlesRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSubmitRoute: DashboardSubmitRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DashboardArticlesArticleIdRoute: DashboardArticlesArticleIdRoute,
  DashboardManageArticlesRoute: DashboardManageArticlesRoute,
  DashboardManageUsersRoute: DashboardManageUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
